### ISSUE TITLE
怎么设置刷新间隔？

### ISSUE THREAD

**Issue by Sylphinford** [SonderXiaoming/pcrjjc_huannai2#10]
看日志，自动查排名是没有刷新间隔的
绑定的少了，就是几秒就对同个人查一次，查询频率太高了
怎么设置刷新的间隔

**Comment by SonderXiaoming** [comment]
utils.py中47行，await asyncio.sleep(1)改成你需要的间隔。
这个就是间隔，即什么都不绑定强制间隔1s，正常是需要注释掉的。

**Comment by Sylphinford** [comment]
懂了 谢谢
